import { forwardRef, useRef, useImperativeHandle } from 'react';
import { StyleSheet, View } from 'react-native';
import WebView, { WebViewMessageEvent } from 'react-native-webview';

// ── xterm.js HTML ──────────────────────────────────────────────────────────────
// Loaded inline so the app works without bundling native assets.
// xterm.js handles rendering; React Native handles the socket connection.
// Data bridge: RN → WebView via injectJavaScript | WebView → RN via postMessage
const TERMINAL_HTML = `<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xterm/xterm@5.5.0/css/xterm.css" />
<script src="https://cdn.jsdelivr.net/npm/@xterm/xterm@5.5.0/lib/xterm.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@xterm/addon-fit@0.10.0/lib/addon-fit.js"></script>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  html, body { width: 100%; height: 100%; background: #1a1b1e; overflow: hidden; }
  #terminal { width: 100%; height: 100%; padding: 6px; }
  .xterm { height: 100%; }
  .xterm-viewport { overflow-y: hidden !important; }
  .xterm-screen { cursor: text; }
</style>
</head>
<body>
<div id="terminal"></div>
<script>
var term = new Terminal({
  theme: {
    background:  '#1a1b1e',
    foreground:  '#c1c2c5',
    cursor:      '#4dabf7',
    selectionBackground: '#373a4060',
    black:       '#25262b',  red:          '#ff6b6b',
    green:       '#69db7c',  yellow:       '#ffd43b',
    blue:        '#4dabf7',  magenta:      '#cc5de8',
    cyan:        '#22b8cf',  white:        '#c1c2c5',
    brightBlack: '#5c5f66',  brightRed:    '#ff6b6b',
    brightGreen: '#69db7c',  brightYellow: '#ffd43b',
    brightBlue:  '#74c0fc',  brightMagenta:'#e599f7',
    brightCyan:  '#3bc9db',  brightWhite:  '#ece9e6',
  },
  fontFamily: '"Menlo", "Monaco", "Courier New", monospace',
  fontSize: 13,
  cursorBlink: true,
  scrollback: 5000,
  allowTransparency: false,
  convertEol: false,
});

var fitAddon = new FitAddon.FitAddon();
term.loadAddon(fitAddon);
term.open(document.getElementById('terminal'));

function rn(obj) {
  window.ReactNativeWebView.postMessage(JSON.stringify(obj));
}

// Initial resize + fix iOS keyboard injection
setTimeout(function() {
  fitAddon.fit();
  // Prevent iOS autocorrect/autocapitalize from injecting characters
  var ta = document.querySelector('.xterm-helper-textarea');
  if (ta) {
    ta.setAttribute('autocorrect', 'off');
    ta.setAttribute('autocomplete', 'off');
    ta.setAttribute('autocapitalize', 'none');
    ta.setAttribute('spellcheck', 'false');
    ta.setAttribute('inputmode', 'none');
  }
  rn({ type: 'ready', cols: term.cols, rows: term.rows });
  // Don't auto-focus — user taps to show keyboard
}, 150);

// Touch → scroll (vertical swipe) or focus (tap)
var _tsY = 0, _tsX = 0, _didScroll = false;
document.getElementById('terminal').addEventListener('touchstart', function(e) {
  _tsY = e.touches[0].clientY;
  _tsX = e.touches[0].clientX;
  _didScroll = false;
}, { passive: true });

document.getElementById('terminal').addEventListener('touchmove', function(e) {
  var dy = _tsY - e.touches[0].clientY;
  var dx = Math.abs(_tsX - e.touches[0].clientX);
  if (Math.abs(dy) > dx && Math.abs(dy) > 4) {
    _didScroll = true;
    term.scrollLines(Math.round(dy / 22));
    _tsY = e.touches[0].clientY;
    _tsX = e.touches[0].clientX;
    e.preventDefault();
  }
}, { passive: false });

document.getElementById('terminal').addEventListener('touchend', function() {
  if (!_didScroll) {
    // Tap (no scroll) → focus + re-enable keyboard
    var ta = document.querySelector('.xterm-helper-textarea');
    if (ta) ta.removeAttribute('inputmode');
    term.focus();
  }
}, { passive: true });

// Resize observer (keyboard open/close, orientation change)
var ro = new ResizeObserver(function() {
  fitAddon.fit();
  rn({ type: 'resize', cols: term.cols, rows: term.rows });
});
ro.observe(document.body);

// User keyboard input
// Filter out DA responses auto-generated by xterm.js (\x1b[?1;2c, \x1b[>0;276;0c, etc.)
// These are terminal capability replies, not user input — forwarding them causes
// garbage text to appear in running applications (tmux, vim, Gemini CLI...).
term.onData(function(data) {
  if (/^\x1b\[[?>][0-9;]*c$/.test(data)) return;
  rn({ type: 'input', data: data });
});

// Messages from React Native
function onMsg(event) {
  try {
    var msg = JSON.parse(event.data);
    if      (msg.type === 'data')  { term.write(msg.data); }
    else if (msg.type === 'focus') { term.focus(); }
    else if (msg.type === 'clear') { term.clear(); }
    else if (msg.type === 'reset') { term.reset(); }
  } catch(e) {}
}
window.addEventListener('message', onMsg);      // iOS
document.addEventListener('message', onMsg);    // Android
</script>
</body>
</html>`;

export type TerminalWebViewRef = {
  writeData: (data: string) => void;
  focus: () => void;
  blur: () => void;
  clear: () => void;
  reset: () => void;
  scrollLines: (n: number) => void;
  scrollWheel: (deltaY: number) => void;
};

type Props = {
  onInput: (data: string) => void;
  onResize: (cols: number, rows: number) => void;
  onReady: (cols: number, rows: number) => void;
};

const TerminalWebView = forwardRef<TerminalWebViewRef, Props>(
  ({ onInput, onResize, onReady }, ref) => {
    const webViewRef = useRef<WebView>(null);

    useImperativeHandle(ref, () => ({
      writeData: (data: string) => {
        // injectJavaScript is the only way to push data INTO a WebView from RN
        const escaped = JSON.stringify(data);
        webViewRef.current?.injectJavaScript(`term.write(${escaped}); true;`);
      },
      focus: () => {
        webViewRef.current?.injectJavaScript(`term.focus(); true;`);
      },
      clear: () => {
        webViewRef.current?.injectJavaScript(`term.clear(); true;`);
      },
      reset: () => {
        webViewRef.current?.injectJavaScript(`term.reset(); true;`);
      },
      blur: () => {
        webViewRef.current?.injectJavaScript(`document.activeElement?.blur(); true;`);
      },
      scrollLines: (n: number) => {
        webViewRef.current?.injectJavaScript(`term.scrollLines(${n}); true;`);
      },
      scrollWheel: (deltaY: number) => {
        // Simulates a mouse wheel event. TUI apps (tmux, vim, gemini-cli) 
        // that support mouse will respond to this even in the alternate buffer.
        const js = `
          var el = document.querySelector('.xterm-screen');
          if (el) {
            el.dispatchEvent(new WheelEvent('wheel', {
              deltaY: ${deltaY},
              deltaMode: 0,
              bubbles: true,
              cancelable: true
            }));
          }
          true;
        `;
        webViewRef.current?.injectJavaScript(js);
      },
    }));

    const handleMessage = (event: WebViewMessageEvent) => {
      try {
        const msg = JSON.parse(event.nativeEvent.data);
        if (msg.type === 'input') onInput(msg.data);
        else if (msg.type === 'resize') onResize(msg.cols, msg.rows);
        else if (msg.type === 'ready') onReady(msg.cols, msg.rows);
      } catch (_) {}
    };

    return (
      <View style={styles.container}>
        <WebView
          ref={webViewRef}
          source={{ html: TERMINAL_HTML }}
          style={styles.webview}
          onMessage={handleMessage}
          scrollEnabled={false}
          showsVerticalScrollIndicator={false}
          showsHorizontalScrollIndicator={false}
          originWhitelist={['*']}
          javaScriptEnabled
          domStorageEnabled
          hideKeyboardAccessoryView
          allowsInlineMediaPlayback
          overScrollMode="never"
        />
      </View>
    );
  }
);

const styles = StyleSheet.create({
  container: { flex: 1 },
  webview: { flex: 1, backgroundColor: '#1a1b1e' },
});

export default TerminalWebView;
